export const SELECTOR = {
    APP:"app",
    MAIN:"main",
    CREW_TAB: "crew-tab",
    TEAM_TAB: "team-tab",
    MATCHING_SECTION:"matching-section",
    CREW_TAB_DETAIL:"crew-tab-detail",
    FRONTEND_COURSE_INPUT: "frontend-course",
    BACKEND_COURSE_INPUT: "backend-course",
    CREW_NAME_INPUT: "crew-name-input",
    ADD_CREW_BUTTON: "add-crew-button",
    COURSE_SELECT: "course-select",
    MISSION_SELECT: "mission-select",
    SHOW_TEAM_MATCHER_BUTTON: "show-team-matcher-button",
    TEAM_MEMBER_COUNT_INPUT: "team-member-count-input",
    MATCH_TEAM_BUTTON: "match-team-button",
};